name: ci

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn --frozen-lockfile --no-progress --non-interactive
      - run: yarn lint
      - run: yarn test --runInBand
      - run: yarn build

      - name: Deploy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && github.repository == 'denodev/upgrade-helper'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
